### ISSUE TITLE
what is a visit?

### ISSUE THREAD

**Issue by ebridge2** [muschellij2/I2C2#2]
Hey guys,
What exactly is a visit vs an id in I2C2? I assume this corresponds to the notion of an id being a subject id and a visit being a scanning session?

**Comment by hcshou** [comment]
Hi Eric,

Yes id corresponds to subject id and visit means numbers of repeated scanning sessions or longitudinal follow-ups.

Best,
Haochang

**Comment by ebridge2** [comment]
Thanks!
