### ISSUE TITLE
Module i2c-2 error on new installed kernel (5.0.0-21-generic)

### ISSUE THREAD

**Issue by ghost** [muschellij2/I2C2#4]
Hi!

I installed a new kernel, version 5.0.0-21-generic.

On boot, systemd shows me this error:
kernel: [ 14.509890] i2c i2c-2: SMBus Timeout!
kernel: [ 14.509952] i2c i2c-2: Failed reset at end of transaction (01)
kernel: [ 14.510064] i2c i2c-2: Failed! (01)

I blacklisted these i2c modules but this did not help. i2c-2 error is still present

at boot.

blacklist i2c_algo_bit
blacklist i2c_core
blacklist i2c_dev
blacklist i2c_i801
blacklist i2c_hid
blacklist i2c_piix4

How to fix these errors on boot?

Please help, thanks!

**Comment by muschellij2** [comment]
I don't think this is the right repo - this is for the image intraclass correlation (I2C2) - a statistical methodology.
